### ISSUE TITLE
Using getOrSet() throw an error

### ISSUE THREAD

**Issue by CaptainPalapa** [coldbox-modules/cbstorages#18]
## What are the steps to reproduce this issue?
1. … Instantiate with 
2. … Attempt to use getOrSet()

`<cfset variables.cs = getInstance( 'cookieStorage@cbstorages' ) />
<cfdump var='#variables.cs.getOrSet( 'sdData', { "name": "", "choices": {} } )#' />
`

## What happens?
Error is thrown, 

## What were you expecting to happen?
Not an error.

## Any other comments?
It appears that the problem is that variables.lockname is not defined.  There is no reference to "lockname" anywhere in the file nor in the implemented file.  I'm guessing there aren't any test cases that support this feature?

\modules\cbstorages\models\AbstractStorage.cfc

![image](https://github.com/coldbox-modules/cbstorages/assets/7297293/69b9f5ba-83ec-407f-89d5-140394d71e81)

## What versions are you using?
**Operating System:** WIndows 11, Lucee 6.01+, Commandbox 6.0.0+00787
**Package Version:** 3.01 Snapshot

**Comment by lmajano** [comment]
Fixed on 3.1.0

**Comment by CaptainPalapa** [comment]
Sorry for not adding anything about the module or file in the subject.
